//user reducer types
export const GET_FIRST_PAGE_DATA = "GET_FIRST_PAGE_DATA";
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const GET_MESSAGES = 'GET_MESSAGES'
export const SET_MESSAGE_SENDER_ID = 'SET_MESSAGE_SENDER_ID'
export const SET_MESSAGE_SENDER_NAME = 'SET_MESSAGE_SENDER_NAME'
export const POST_MESSAGE = 'POST_MESSAGE'
export const GET_SALARIES_BY_TITLE_LOC = 'GET_SALARIES_BY_TITLE_LOC'

//company reducer types

//admin reducer types
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS'
export const MARK_REVIEW_APPROPRIATE = 'MARK_REVIEW_APPROPRIATE'
export const MARK_REVIEW_INAPPROPRIATE = 'MARK_REVIEW_INAPPROPRIATE'
export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS'
export const MARK_PHOTO_APPROPRIATE = 'MARK_PHOTO_APPROPRIATE'
export const MARK_PHOTO_INAPPROPRIATE = 'MARK_PHOTO_INAPPROPRIATE'
